1. You are managing the electronics section of store. You need to track the sales of **3products** . heaphones ,smartphones,and speakers ober **4 days** (monday to thursday)
Row 0 : Headphones
Row 2 : Smartphones 
Row 3 : Speakers

**Task 1.1:** Create a 1D NumPy array called cost price containing the prices of 3 items : [1500,3000,5000] 
**Task 1.2:** Create a 2D NumPy array called daily sales representing the number of units sold:
              data id given as table just have to write matrix.
**Task 1.3:** Print shape and dimension of both arrays

In [2]:
import numpy as np
arr = np.array([1500,3000,5000])          

In [3]:
arr2 = np.array([[10,15,8,12],
                 [5,7,4,6],
                 [2,3,2,4]])

In [4]:
np.shape(arr)

(3,)

In [5]:
np.shape(arr2)

(3, 4)

In [6]:
np.ndim(arr)

1

In [7]:
np.ndim(arr2)

2

**Task 2.1** The manger decides to add **2 "bonus" units** to every product's daily sale for a holiday report. Add 2 to the entire daily sales array.

Task 2.2. Calculate the total revenue for each day
Multiply the cost price array by the daily sales matrix
Observe how numpy handles the ultiplication of 1 d and 2d arrays
Task 2.3 (Scaling) use np.sqrt() on the sale sdata to find the sqaure root of all sales values fo statistical curve.

In [ ]:
#2.1
print(arr2 +2)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [ ]:
#2.2
cost_price = np.array([20, 30, 15, 25])
revenue = arr2 * cost_price
print(revenue)

[[200 450 120 300]
 [100 210  60 150]
 [ 40  90  30 100]]


In [10]:
#2.3
print(np.sqrt(arr2))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


#Slicing and Indexing
#Task 3.1- Access to sales data for Smartwatches (Row 1) for all 4 days. 
#Task 3.2 - Access to sales data for te first two days(Monday and Tuesday). 
#Task 3.3- Using slicing extract a 2x2 sub array representin te sales of eadpones and smartpons for Monday anmd tuesday

#Task 3.1 — Smartwatches (Row 1, all 4 days)
👉 Row index starts from 0 in NumPy.

Row 1 = second row:

In [11]:
print(arr2[1])

[5 7 4 6]


Task 3.2 — First two days (Monday & Tuesday)

👉 First 2 columns:

💡 Meaning:

:  → all rows
0:2 → column 0 and 1

In [12]:
print(arr2[:, 0:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


✅ Task 3.3 — 2×2 subarray (Headphones & Smartphones, Mon–Tue)

👉 Rows 1–2 and columns 0–1:

1:3 → row 1 and 2
0:2 → column 0 and 1


In [13]:
print(arr2[1:3, 0:2])

[[5 7]
 [2 3]]


Row → arr2[row_index]
Column → arr2[:, col_index]
Slice → arr2[row_start:row_end, col_start:col_end]


Task C1 : Pass / Fail mapping
- Create a status matrix where:
-- Mark >=50 ->1 (Pass)
-- Mark <=50 ->0 (Fail)

Task C2: Data Cleaning
- To standardize failing grades , replace all the marks below 40 with the value of 0.

# 🎯 NumPy Matrix: Pass/Fail Mapping + Data Cleaning

## 🧠 Step 1: Create a Marks Matrix

A **matrix** is a 2D NumPy array (rows + columns) used to store structured data.

```python
import numpy as np

marks = np.array([
    [35, 50, 72],
    [28, 90, 45]
])
```

👉 This is a **2 × 3 marks matrix**.

---

## ✅ Step 2: Pass / Fail Mapping (Using `np.where()`)

### 🔍 What is `np.where()`?

`np.where()` is used to apply **conditions on the whole matrix at once** (no loops needed 🚀).

📌 Syntax:

```
np.where(condition, value_if_true, value_if_false)
```

👉 It checks every element and assigns values based on the condition.

### 🎯 Our rule:

* Marks ≥ 50 → **1 (Pass)** ✅
* Marks < 50 → **0 (Fail)** ❌

```python
status = np.where(marks >= 50, 1, 0)
print(status)
```

📊 Output:

```
[[0 1 1]
 [0 1 0]]
```

👉 Each mark is converted into **Pass/Fail status**.

---

## 🧹 Step 3: Data Cleaning (Boolean Indexing)

We want to standardize failing grades:

👉 All marks **below 40 → replace with 0**

```python
marks[marks < 40] = 0
print(marks)
```

📊 Output:

```
[[ 0 50 72]
 [ 0 90 45]]
```

💡 This uses **boolean indexing** to update values instantly.

---

## 🧪 Final Combined Code

```python
import numpy as np

# Create marks matrix
marks = np.array([
    [35, 50, 72],
    [28, 90, 45]
])

# Pass/Fail mapping
status = np.where(marks >= 50, 1, 0)

# Data cleaning
marks[marks < 40] = 0

print("Status Matrix:")
print(status)

print("Cleaned Marks Matrix:")
print(marks)
```

---

## 🚀 Why Use `np.where()`?

`np.where()` is powerful because it:

✨ Applies conditions to the entire matrix at once
⚡ Avoids slow loops
📊 Is widely used in ML data preprocessing
🎯 Helps in classification & feature transformation

👉 In short: **Fast + Clean + Smart coding!**


In [1]:
import numpy as np
# Create a 2D matrix of student marks
marks = np.array([
    [35,50,72],
    [28,90,45]
])
# -----------------------------
# Task C1: Pass / Fail mapping
# -----------------------------

# Create a status matrix:
# Marks >= 50 → 1 (Pass)
# Marks < 50 → 0 (Fail)
status = np.where(marks >= 50, 1, 0)

# Print pass/fail matrix
print("Status Matrix:")
print(status)


Status Matrix:
[[0 1 1]
 [0 1 0]]


In [ ]:
# -----------------------------
# Task C2: Data Cleaning
# -----------------------------

# Replace all marks below 40 with 0
# This standardizes failing grades
marks[marks < 40] = 0

# Print cleaned marks matrix
print("Cleaned Marks Matrix:")
print(marks)

Task D1: Grade Allocation
apply a grading system based on the student Average
- Avg >= 85: Grade A (Score: 10)
- Avg >= 70: Grade B (Score: 8)
- Avg >= 50: Grade C (Score: 6)
- Below 50: No Grade  (Score: 0)

requirement: Use nested conditional logic within numpy