In [ ]:
print("hello")



hello


In [2]:
print("I am learning AI and ML")

I am learning AI and ML


In [3]:
heights = [135,120,140,150,155,170,190]
tall_people = []
threshhold = 150
for i in heights:
    if i>=threshhold:
        tall_people.append(i)

print(tall_people)

[150, 155, 170, 190]


In [4]:
age =18
branch = "CSE"
print(type(age))
print(type(branch))

<class 'int'>
<class 'str'>


In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
print("")

In [4]:
import numpy as np

In [6]:
#create an empty array
arr = np.array([])
print(arr)

[]


In [8]:
#create an array which hold integers 2,3,4,5,6,7,8,9
arr = np.array([2,3,4,5,6,7,8,9])
print(arr)

[2 3 4 5 6 7 8 9]


In [9]:
list = [10,20,30,40,50]
import numpy as mp
arr = np.array(list)
print(arr)

[10 20 30 40 50]


In [ ]:
list = [10,20,30,40,50]
arr2 = np.array(list)
print(arr2)
print(type(arr2)) 

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [12]:
array = np.array([1,2,3,4,5])
print("Dimension:",array.ndim)
print("Number of elements:",array.size)
print("The data type of the array:",array.dtype)

Dimension: 1
Number of elements: 5
The data type of the array: int64


In [15]:
list = [1,'Tejjal',2.5]
arr = np.array(list)
print(arr)
print(type(arr))

['1' 'Tejjal' '2.5']
<class 'numpy.ndarray'>


In [14]:
#2D ARRAY
arr2D = np.array([ [] , [] , [] ])
array2D = np.array([ [1,2] , [3,4] ])

print(array2D)
print(type(array2D))
print(array2D.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


In [1]:
import numpy as np
a = np.array([1,2,4])
a

array([1, 2, 4])

In [ ]:
print(a.shape)
(3,)
print(a.ndim) #1 d array

(3,)
1


In [ ]:
#using slicing have fetch the value 

In [2]:
import numpy as np
arr = np.array([[1,2,3] , [3,2,4] , [4,6,5]])
print(arr)
print(type(arr))
print(arr.ndim)

[[1 2 3]
 [3 2 4]
 [4 6 5]]
<class 'numpy.ndarray'>
2


In [ ]:
#arange function. it create an array of numbers in sequence
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(100,501)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
       256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 28

In [5]:
#10 multiples of 5
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [6]:
#ONE'S in numpy
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#in the form of tuple
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# identity matrix diagonal elements are 1 rest are 0
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# np.full() creates a NUmpy array of given shape.. and fills every position with the same value
np.full((2,2) , 10)

array([[10, 10],
       [10, 10]])

In [ ]:
# creates a numpy array of evenly spaced numbers from 1 to 5 including both 1 and 5 by default numpy makes 50 values 
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [19]:
np.random.randint*(1,100)

TypeError: can't multiply sequence by non-int of type 'method'

In [ ]:
#creates a 4x4 matric filled with random decimal numbers between 0 and 1.
np.random.rand(4,4)

array([[0.64227452, 0.51514518, 0.28739842, 0.40869195],
       [0.60935777, 0.19032377, 0.02587159, 0.23406057],
       [0.39492093, 0.62360343, 0.01598234, 0.91183871],
       [0.73182299, 0.69347949, 0.74363159, 0.19152223]])

In [ ]:
# creates a numpy array of 10 random decimal numebrs drawn from a normal distribution
np.random.randn(10)

array([ 0.86311855,  0.07633516, -0.08456182, -1.15433126,  1.37857119,
        0.44694125,  0.8344926 , -0.34013694, -1.31171639,  0.03359548])

In [ ]:
# creates the numpy array with random integers between 1 and 999
a = np.random.randint(1,1000,10)
print(a)

[705  52 395 306 222 218 908 672 214 341]


In [ ]:
#returns the index of the largest value in the array a , not the value itself
np.argmax(a)

np.int64(6)

In [ ]:
#finds the largest value in the numpy array a
np.max(a)

np.int64(908)

In [ ]:
# finds the smallest min value in numpy array a
np.min(a)

np.int64(52)

In [3]:
import numpy as np
import pandas as pd


In [8]:
#reads csv file and store it into pandas dataFrame called df
df = pd.read_csv("train.csv")

In [ ]:
df.head();

In [ ]:
# displays the dataFrame, it shows the table of data
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# it shows the first five rows of your dataFrame df by default
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
# last 5 rows
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [10]:
# (rows,coloumns)
df.shape

(891, 12)

In [11]:
# coloumn names
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [ ]:
# Data summary (information)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    str    
 4   Sex          891 non-null    str    
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    str    
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str    
 11  Embarked     889 non-null    str    
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB


In [ ]:
# statistical summary table of dataset.  T is for transpose of row coloumn and here data is only of numerical .. not for string data (str)
df.describe().T

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

In [16]:
#only summarise object - type columns (str)
df.describe(include = "object").T

/var/folders/rb/2ztkxrwj1zvb99krf4ndg2d40000gn/T/ipykernel_22748/1452817794.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object").T


count unique                      top freq
Name       891    891  Braund, Mr. Owen Harris    1
Sex        891      2                     male  577
Ticket     891    681                   347082    7
Cabin      204    147                       G6    4
Embarked   889      3                        S  644

In [ ]:
#similar to df.info()
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [ ]:
# selects all numeric (int and float ) coloumns from dataFrame and stores them in num_col.
num_col = df.select_dtypes(include = ["int64" , "float64"])
num_col

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [21]:
df.describe(include = "object").T

/var/folders/rb/2ztkxrwj1zvb99krf4ndg2d40000gn/T/ipykernel_22748/726139619.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object").T


count unique                      top freq
Name       891    891  Braund, Mr. Owen Harris    1
Sex        891      2                     male  577
Ticket     891    681                   347082    7
Cabin      204    147                       G6    4
Embarked   889      3                        S  644

In [23]:
#selects all categorical (text/object) columns fro dataFrame and stores them in cat_col
cat_col = df.select_dtypes(include = "object")
cat_col

/var/folders/rb/2ztkxrwj1zvb99krf4ndg2d40000gn/T/ipykernel_22748/1740095147.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df.select_dtypes(include = "object")


Name     Sex  \
0                              Braund, Mr. Owen Harris    male   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                               Heikkinen, Miss. Laina  female   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                             Allen, Mr. William Henry    male   
..                                                 ...     ...   
886                              Montvila, Rev. Juozas    male   
887                       Graham, Miss. Margaret Edith  female   
888           Johnston, Miss. Catherine Helen "Carrie"  female   
889                              Behr, Mr. Karl Howell    male   
890                                Dooley, Mr. Patrick    male   

               Ticket Cabin Embarked  
0           A/5 21171   NaN        S  
1            PC 17599   C85        C  
2    STON/O2. 3101282   NaN        S  
3              113803  C123        S  
4              373450   NaN        S  
..                ...   ...      ...  
886            211536   NaN        S  
887            112053   B42        S  
888        W./C. 6607   NaN        S  
889            111369  C148        C  
890            370376   NaN        Q  

[891 rows x 5 columns]

In [ ]:
#counts how many times each unique value in the column (Sex) appears and shows their frequencies
#df.columnName.value_counts()
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [26]:
#if there is any missing value in your dataset or not
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:

df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

#2D ARRAY

In [3]:
#here we are making 2d array and printing , mat is a variable name
import numpy as np
mat = np.array([[1,2,3], [4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
#it creates a 1D numpy array of length 5 , where all values are 0
#floating point by default
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#creates 1D numpy array of length 5 all values 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#creates 3D array , all values 0 
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#(start,end) start from 0 to 10 btt 10 is excluded
#10 is excluded
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#(start,end,skip). 1 se start 10 btt 10 excluded.. skip 2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
#(start value,end value,total no. of values)
#creates 1 D array with 5 evenly spaced values between 0 and 1(both included)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

ARRAY PROPERTIES

In [12]:
arr = np.array([[1,2,3] ,
               [4,5,6]])

In [ ]:
# ndim checks whether its a 1 D ,2D ,3D dimentional array
print(arr.ndim) #dimension
print(arr.shape) #rows,columns
print(arr.size) #total elements
print(arr.dtype) #datatype of element inside array

2
(2, 3)
6
int64


**TYPE CONVERSION**

In [ ]:
arr = np.array([1.2 , 2.5 , 3.7])
arr_int = arr.astype(int) #astype(int) converts each float to integer
print(arr_int)

[1 2 3]


INDEXING AND SLICING

In [15]:
arr = np.array([10,20,30,40])
print(arr[0]) #indexing
print(arr[-1])

10
40


# 1D SLICING

In [ ]:
#arr[start : stop : step]
print(arr[1:3]) #from index 1 to 3 (3 not included)
print(arr[:2]) #from start to 2 (2 not included)
print(arr[::2]) #start to end ,step=2 

[20 30]
[10 20]
[10 30]


2D INDEXING

In [ ]:
                # 0 1 2
mat = np.array([[1,2,3],    #0
                [4,5,6],    #1
                [7,8,9]])   #2
print(mat[0,1]) 
print(mat[1])

2
[4 5 6]


In [ ]:
# mat[rows,columns]
# : -> select all rows
# 1 -> select column index 1 (2nd column) 
print(mat[:,1])   #column 1

[2 5 8]


COPY()

In [ ]:
a = np.array([1,2,3])
b = a.copy()   #copy
# a.copy()-> creatyes a new , seperate array in memory
# b is independent of a 
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [ ]:
a = np.array([1,2,3])
b = a       # this logic is not safe
# here ,it is not a copy , just a another reference
#a and b are linked here
b[0] =99
print(a)

[99  2  3]


BASIC ARRAY OPERATIONS (VECTOR POWER)

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


SCALAR OPERATIONS

In [ ]:
#scalar is a single number.. apply operation with single number to every element of an array
print(a + 10)
print(a * 2)

[11 12 13]
[2 4 6]


unfus UNIVERSAL FUNCTIONS

In [ ]:
arr = np.array([1,4,9,16]) #creates a numpy array
print(np.sqrt(arr)) # square root of each element
print(np.log(arr)) # natuiral log (ln) of each element
print(np.exp(arr)) # e^x (Exponential) of each element
print(np.max(arr)) #maximum value in array
print(np.min(arr)) #minimum value in array
print(np.mean(arr)) #average (mean) of array values
print(np.sum(arr)) #sum of all elements
print(np.std(arr)) #standard deviation 

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


BOOLEAN INDEXING

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr [arr>25]) #prints elements greater than 25


[30 40 50]


In [ ]:
print(arr>25) #checks each element in arr and returns true and false

[False False  True  True  True]


BROADCASTING RULE

In [ ]:
# NumPy automatically expands the smaller array

In [ ]:
arr = np.array([1,2,3,4])
print(arr+10) #adds 10 to each element using broadcasting

[11 12 13 14]


In [ ]:
mat = np.array([[1,2,3],
                [4,5,6]])
print(mat+10) # adds 10 to every eklement using broadcasting

[[11 12 13]
 [14 15 16]]


**MATRIX MULTIPLICATION**

In [ ]:
# matrix multiplication using np.dot() by taking dot product
A = np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
             [7,8]])
print(np.dot(A,B))       # not a element wise multiplication

[[19 22]
 [43 50]]


In [ ]:
#transpose (changing row to column)
print(A.T)

[[1 3]
 [2 4]]


RANDOM MODULE

In [ ]:
#creates a 1D array of 5 random numbers between 0 and 1 (0 included, 1 excluded)
np.random.rand(5)

array([0.45721186, 0.9237511 , 0.35441274, 0.11614001, 0.21926721])

In [ ]:
#creates 2D array array shape 3x3 filled with random floating point numbers between 0 and 1
np.random.rand(3,3)

array([[0.85672282, 0.49621179, 0.86090406],
       [0.6665997 , 0.64024826, 0.27496431],
       [0.21281815, 0.05711585, 0.89369793]])

In [ ]:
# generates 10 random integers between 1 and 99 
np.random.randint(1,100,10)

array([30, 33, 55, 45, 78, 97, 13, 20, 38, 24])

In [35]:
#2D version
np.random.randint(1,100,(3,3))

array([[15, 27, 83],
       [17, 69,  3],
       [37, 55, 19]])

RESHAPING ARTRAYS

In [ ]:
arr = np.arange(12)
print(arr.reshape(3,4))  # turns it into 3x4 matrix

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

DATASET

In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("tip.csv") #read the dataset

In [ ]:
df #displays the dataframe

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df.head() #first five rows of dataframe

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.tail() #last 5 rows of dataframe

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.shape #(rows,columns)

(244, 7)

In [ ]:
df.columns #column names

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [ ]:
df.info() #data summary

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str    
 3   smoker      244 non-null    str    
 4   day         244 non-null    str    
 5   time        244 non-null    str    
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB


In [ ]:
df.describe().T #statistical summary

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [ ]:
#only summarise object type colums (string vale)
df.describe(include = "object").T 

/var/folders/rb/2ztkxrwj1zvb99krf4ndg2d40000gn/T/ipykernel_20065/726139619.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include = "object").T


count unique     top freq
sex      244      2    Male  157
smoker   244      2      No  151
day      244      4     Sat   87
time     244      2  Dinner  176

In [ ]:
df.dtypes #datatypes similar as df.info()

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [ ]:
num_col = df.select_dtypes(include = ["int64" , "float64"]) # only numerical columns from dataframe and store them in num_col
num_col

total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]

In [ ]:
cat_col = df.select_dtypes(include = "object") #only categoprical columns from dataframwe and store it into cat_col
cat_col

/var/folders/rb/2ztkxrwj1zvb99krf4ndg2d40000gn/T/ipykernel_20065/3143052346.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = df.select_dtypes(include = "object")


sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [ ]:
#df.columnName.value_counts()
df.day.value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df.isnull().sum() #is ther eany missing value in dataset or not

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [17]:
df.isnull()

total_bill    tip    sex  smoker    day   time   size
0         False  False  False   False  False  False  False
1         False  False  False   False  False  False  False
2         False  False  False   False  False  False  False
3         False  False  False   False  False  False  False
4         False  False  False   False  False  False  False
..          ...    ...    ...     ...    ...    ...    ...
239       False  False  False   False  False  False  False
240       False  False  False   False  False  False  False
241       False  False  False   False  False  False  False
242       False  False  False   False  False  False  False
243       False  False  False   False  False  False  False

[244 rows x 7 columns]

**T**