In [1]:
# -----------------------------------
# Task 3: Slicing and Indexing
# -----------------------------------
import numpy as np
# Task 3.1: Access sales data for Smartwatches (Row 1, all 4 days)
# Row index starts from 0 in NumPy
arr2 = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])
print("Task 3.1 - Smartwatches sales:")
print(arr2[1])


# -----------------------------------

# Task 3.2: Access sales data for the first two days (Monday & Tuesday)
# : means all rows
# 0:2 means first two columns

print("\nTask 3.2 - Sales for Monday & Tuesday:")
print(arr2[:, 0:2])


# -----------------------------------

# Task 3.3: Extract 2x2 subarray
# (Headphones & Smartphones for Monday & Tuesday)
# Rows 0:2 → first two rows
# Columns 0:2 → first two columns

print("\nTask 3.3 - 2x2 subarray:")
print(arr2[0:2, 0:2])


# -----------------------------------
# Indexing reference
# -----------------------------------
# Row access → arr2[row_index]
# Column access → arr2[:, col_index]
# Slicing → arr2[row_start:row_end, col_start:col_end]


Task 3.1 - Smartwatches sales:
[5 7 4 6]

Task 3.2 - Sales for Monday & Tuesday:
[[10 15]
 [ 5  7]
 [ 2  3]]

Task 3.3 - 2x2 subarray:
[[10 15]
 [ 5  7]]
