#**Part C - BroadCasting & Policy Rules**

Policy Rule - if electricity usage on any day is greater than 550 units , a 20% surcharge is applied.

Task C1
create a new array penalized usage such that
- Values > 550 -> multiplied by 1.20
- All other values remain unchanged

Constraints: - Must use np.where. No loops Allowed

In [2]:
# ================================
# Part C: Broadcasting & Policy Rule
# ================================
import numpy as np

# ================================
# Step 1: Create electricity array
# ================================

# Generate 4x7 random electricity usage data
electricity = np.random.randint(120, 651, (4, 7))

print("Electricity Usage:")
print(electricity)




# Policy:
# If electricity usage > 550 → apply 20% surcharge

# Task C1: Create penalized usage array

penalized_usage = np.where(
    electricity > 550,     # condition: check values greater than 550
    electricity * 1.20,    # apply 20% surcharge
    electricity            # keep original values
)

# Display results
print("Original Electricity Usage:")
print(electricity)

print("\nPenalized Electricity Usage:")
print(penalized_usage)


Electricity Usage:
[[289 600 385 136 518 648 138]
 [403 212 278 399 416 615 642]
 [476 548 582 233 601 500 129]
 [255 219 218 341 292 590 510]]
Original Electricity Usage:
[[289 600 385 136 518 648 138]
 [403 212 278 399 416 615 642]
 [476 548 582 233 601 500 129]
 [255 219 218 341 292 590 510]]

Penalized Electricity Usage:
[[289.  720.  385.  136.  518.  777.6 138. ]
 [403.  212.  278.  399.  416.  738.  770.4]
 [476.  548.  698.4 233.  721.2 500.  129. ]
 [255.  219.  218.  341.  292.  708.  510. ]]


# ⚡ Part C — Broadcasting & Policy Rule

## 🧠 Problem Understanding

The university applies a **20% surcharge** when electricity usage exceeds **550 units**.

We must create a new array where:

* Values > 550 → multiplied by **1.20**
* Other values remain unchanged
* No loops allowed

---

## 🔍 Step 1: Understanding `np.where()`

```python
np.where(condition, value_if_true, value_if_false)
```

This function checks each element and chooses a value based on a condition.

Meaning:

* If condition is **True** → use value_if_true
* Else → use value_if_false

---

## 🔍 Step 2: Apply the Condition

```python
electricity > 550
```

This creates a **True/False matrix** showing where the surcharge applies.

---

## 🔍 Step 3: Broadcasting

```python
electricity * 1.20
```

NumPy multiplies **every element** by 1.20 automatically.

This is called **broadcasting** — applying a single number to an entire array.

---

## ✅ Final Operation

```python
penalized_usage = np.where(
    electricity > 550,
    electricity * 1.20,
    electricity
)
```

This creates a new matrix with surcharge applied only where needed.

---

## ⭐ Key Concepts Learned

* Conditional selection using `np.where()`
* Broadcasting for scalar multiplication
* Vectorized operations without loops

---

## 🎯 Viva Line

> Broadcasting and `np.where()` allow efficient conditional updates on arrays without using loops.
