Task B1: Hostel-wise Metrics
Find the average electricity usage per hostel, the maximum usage per hostel, and identify which hostel has the highest average usage.

Task B2: Day-wise metrics
Calculate the total electricity consumption per day and identify the day with highest total campus consumption.

requirement: students choose the correct axis values for each operation

# ⚡ Electricity Usage Case Study — Complete Explanation

We are analyzing electricity usage of **4 hostels over 7 days** using NumPy.

👉 Rows = hostels
👉 Columns = days
👉 Shape = **(4, 7)**

---

## 🧠 Step 1: Import NumPy

```python
import numpy as np
```

We import NumPy because it helps us work with **arrays and numerical data efficiently**.

---

## 🧠 Step 2: Create the Dataset

```python
electricity = np.random.randint(120, 651, (4, 7))
```

### 🔍 Explanation

* `np.random.randint()` → generates random integers
* `120` → starting value (included)
* `651` → ending value (excluded)
* `(4, 7)` → shape of the array

So this creates a **4 × 7 matrix** with values between **120 and 650**.

---

## 🧠 Step 3: Array Attributes

```python
electricity.shape
electricity.ndim
electricity.size
electricity.dtype
```

### 📌 Meaning

* **shape** → size of array (rows × columns)
* **ndim** → number of dimensions
* **size** → total elements in array
* **dtype** → data type of elements

---

## 🏠 Task B1: Hostel-wise Metrics

We calculate statistics **per hostel** (row-wise).

### ⭐ Important Concept: Axis

* **axis = 1 → row-wise**
* **axis = 0 → column-wise**

---

### ✅ Average per Hostel

```python
avg_hostel = np.mean(electricity, axis=1)
```

* `np.mean()` calculates average
* `axis=1` means average across each row

---

### ✅ Maximum per Hostel

```python
max_hostel = np.max(electricity, axis=1)
```

* `np.max()` finds maximum value
* Done row-wise

---

### ✅ Hostel with Highest Average

```python
highest_avg_hostel = np.argmax(avg_hostel)
```

* `np.argmax()` returns index of largest value
* Tells which hostel has highest average

---

## 📅 Task B2: Day-wise Metrics

We calculate statistics **per day** (column-wise).

---

### ✅ Total Consumption per Day

```python
total_per_day = np.sum(electricity, axis=0)
```

* `np.sum()` adds values
* `axis=0` means column-wise sum

---

### ✅ Day with Highest Consumption

```python
highest_day = np.argmax(total_per_day)
```

* Finds index of highest total day

---

## ⭐ Axis Memory Trick

```
axis = 0 → go down (columns)
axis = 1 → go across (rows)
```

---

## 🎯 Final Viva Summary

* NumPy arrays store structured numerical data
* `np.mean`, `np.max`, `np.sum` compute statistics
* `np.argmax` finds position of maximum value
* Axis determines direction of calculation


In [1]:
import numpy as np

# ====================================
# Task A1: Create electricity dataset
# ====================================

# Create a 4x7 array with random electricity usage
# Values range from 120 to 650
# Rows = hostels (h1–h4)
# Columns = days (Mon–Sun)

electricity = np.random.randint(120, 651, (4, 7))

print("Electricity Usage Array:")
print(electricity)


# ====================================
# Task A2: Print array attributes
# ====================================

print("\nShape:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total number of elements:", electricity.size)
print("Data type:", electricity.dtype)


# ====================================
# Task B1: Hostel-wise Metrics
# ====================================

# Average electricity usage per hostel (row-wise → axis=1)
avg_hostel = np.mean(electricity, axis=1)

# Maximum usage per hostel (row-wise → axis=1)
max_hostel = np.max(electricity, axis=1)

# Hostel with highest average usage
highest_avg_hostel = np.argmax(avg_hostel)

print("\nAverage usage per hostel:", avg_hostel)
print("Maximum usage per hostel:", max_hostel)
print("Hostel with highest average usage (index):", highest_avg_hostel)


# ====================================
# Task B2: Day-wise Metrics
# ====================================

# Total electricity consumption per day (column-wise → axis=0)
total_per_day = np.sum(electricity, axis=0)

# Day with highest total consumption
highest_day = np.argmax(total_per_day)

print("\nTotal consumption per day:", total_per_day)
print("Day with highest total consumption (index):", highest_day)


Electricity Usage Array:
[[361 201 540 471 496 595 507]
 [560 520 491 210 216 576 204]
 [376 372 281 561 581 411 513]
 [300 384 147 481 232 389 618]]

Shape: (4, 7)
Number of dimensions: 2
Total number of elements: 28
Data type: int64

Average usage per hostel: [453.         396.71428571 442.14285714 364.42857143]
Maximum usage per hostel: [595 576 581 618]
Hostel with highest average usage (index): 0

Total consumption per day: [1597 1477 1459 1723 1525 1971 1842]
Day with highest total consumption (index): 5


# ⚡ Task B: Hostel-wise and Day-wise Metrics

The electricity array has shape **(4, 7)**:

* Rows → Hostels
* Columns → Days

Understanding the **axis** is the key concept.

---

## 🏠 Task B1: Hostel-wise Metrics

To calculate values **per hostel**, we operate **row-wise**.

```python
avg_hostel = np.mean(electricity, axis=1)
max_hostel = np.max(electricity, axis=1)
```

* `axis=1` means operate across columns
* We get one result per row (hostel)

The hostel with the highest average:

```python
highest_avg_hostel = np.argmax(avg_hostel)
```

---

## 📅 Task B2: Day-wise Metrics

To calculate values **per day**, we operate **column-wise**.

```python
total_per_day = np.sum(electricity, axis=0)
```

* `axis=0` means operate down rows
* We get one result per column (day)

The day with highest consumption:

```python
highest_day = np.argmax(total_per_day)
```

---

## ⭐ Axis Memory Trick

* **axis=0 → go down (columns)**
* **axis=1 → go across (rows)**

---

## 🎯 Viva Line

> Choosing the correct axis allows us to compute hostel-wise or day-wise statistics from a 2D dataset.
