Part F - Memory Safety
- Create ref backup = electricity
- Create safe backup = electricity.copy()
- Modify one value in the original electricity array.
- Observe which backups change.

Explanation Required - Why is ref_backup risky? when is .copy() required?

In [2]:
import numpy as np

# ================================
# Step 1: Create electricity array
# ================================

# Generate 4x7 random electricity usage data
electricity = np.random.randint(120, 651, (4, 7))

print("Electricity Usage:")
print(electricity)

# ================================
# Part F: Memory Safety
# ================================

# Step 1: Create reference backup (shares memory)
ref_backup = electricity

# Step 2: Create safe backup (independent copy)
safe_backup = electricity.copy()

# Step 3: Modify original array
electricity[0, 0] = 999

# Step 4: Observe changes
print("Modified Original:")
print(electricity)

print("\nReference Backup (changed):")
print(ref_backup)

print("\nSafe Backup (unchanged):")
print(safe_backup)



Electricity Usage:
[[456 208 257 607 515 326 592]
 [371 499 397 449 538 616 625]
 [600 326 479 606 182 590 241]
 [148 565 495 363 252 123 386]]
Modified Original:
[[999 208 257 607 515 326 592]
 [371 499 397 449 538 616 625]
 [600 326 479 606 182 590 241]
 [148 565 495 363 252 123 386]]

Reference Backup (changed):
[[999 208 257 607 515 326 592]
 [371 499 397 449 538 616 625]
 [600 326 479 606 182 590 241]
 [148 565 495 363 252 123 386]]

Safe Backup (unchanged):
[[456 208 257 607 515 326 592]
 [371 499 397 449 538 616 625]
 [600 326 479 606 182 590 241]
 [148 565 495 363 252 123 386]]


# 🛡️ Part F — Memory Safety (Reference vs Copy)

## 🎯 Objective

Understand how NumPy handles memory when creating backups.

---

## 🔍 Reference Backup

```python
ref_backup = electricity
```

This does **not create a new array**.

It only creates a new **reference** pointing to the same memory.

So:

```
electricity ─┐
             ├──> same memory
ref_backup ──┘
```

Any modification to one affects the other.

---

## 🔍 Safe Backup

```python
safe_backup = electricity.copy()
```

`.copy()` creates a **new independent array**.

```
electricity ──> memory A
safe_backup ──> memory B
```

Changes in the original do not affect the copy.

---

## ⚠️ Why is `ref_backup` risky?

Using reference backup is risky because:

* It can accidentally overwrite important data
* Bugs become hard to detect
* Original data may be lost during processing

Both variables share the same memory.

---

## ✅ When is `.copy()` required?

`.copy()` is required when:

* You want to preserve original data
* You are performing data cleaning or transformations
* You need a safe backup for experiments

It ensures memory independence.

---

## 🎯 Viva Line

> Reference assignment shares memory and is risky, while `.copy()` creates an independent safe backup.
