Task D1: Thinking task
Compare each hostel's daily usage with its own weekly average. Create a boolean matrix where:
- True: Above hostel average
- False: Below or equal to hostel average

Requirement - requires broadcasting of a (4,) array across a (4,7) array. 

In [2]:
# ================================
# Task D1: Compare with hostel averages
# ================================
import numpy as np

# ================================
# Step 1: Create electricity array
# ================================

# Generate 4x7 random electricity usage data
electricity = np.random.randint(120, 651, (4, 7))

print("Electricity Usage:")
print(electricity)



# Step 1: Calculate weekly average per hostel (row-wise)
hostel_avg = np.mean(electricity, axis=1)

# Step 2: Reshape averages to (4,1) for broadcasting
hostel_avg = hostel_avg.reshape(4, 1)

# Step 3: Compare each value with its hostel average
comparison = electricity > hostel_avg

# Display results
print("Hostel Weekly Averages:")
print(hostel_avg)

print("\nBoolean Comparison Matrix:")
print(comparison)


Electricity Usage:
[[228 442 562 338 295 268 522]
 [434 619 276 438 586 272 575]
 [385 433 495 414 396 510 483]
 [612 479 234 618 387 474 621]]
Hostel Weekly Averages:
[[379.28571429]
 [457.14285714]
 [445.14285714]
 [489.28571429]]

Boolean Comparison Matrix:
[[False  True  True False False False  True]
 [False  True False False  True False  True]
 [False False  True False False  True  True]
 [ True False False  True False False  True]]


# 🧠 Task D1 — Comparing Usage with Hostel Averages

## 🎯 Goal

For each hostel, compare daily electricity usage with its **own weekly average**.

We create a boolean matrix:

* **True** → above average
* **False** → below or equal to average

---

## 🔍 Step 1: Calculate Hostel Averages

```python
hostel_avg = np.mean(electricity, axis=1)
```

* `np.mean()` calculates averages
* `axis=1` → row-wise (per hostel)
* Result shape = **(4,)**

---

## 🔍 Step 2: Reshape for Broadcasting

```python
hostel_avg = hostel_avg.reshape(4, 1)
```

We convert shape:

```
(4,) → (4,1)
```

This allows NumPy to broadcast averages across 7 days.

---

## 🔍 Step 3: Element-wise Comparison

```python
comparison = electricity > hostel_avg
```

NumPy broadcasts the (4,1) array across the (4,7) array.

Each hostel is compared with its own average.

---

## ⭐ Broadcasting Idea

```
(4,1) → stretched to → (4,7)
```

Each row average is copied across its row.

---

## 🎯 Result

We get a **boolean matrix** showing which days are above average.

---

## 🎯 Viva Line

> Broadcasting allows a smaller array to expand across a larger array for element-wise comparison.
