Part E - Reshaping & Data Structure

Task E1: Reshape the electricity data into a single row representing weekly usage ( Shape: 1x28).
Task E2: Reshape the same data into 2 rows and 14 columns. Ensure no data is lost or duplicated.

In [1]:
import numpy as np

# ================================
# Step 1: Create electricity array
# ================================

# Generate 4x7 random electricity usage data
electricity = np.random.randint(120, 651, (4, 7))

print("Electricity Usage:")
print(electricity)



# ================================
# Part E: Reshaping & Data Structure
# ================================

# Task E1: Reshape into 1 × 28 (single row)
reshape_1x28 = electricity.reshape(1, 28)

print("Reshaped to 1x28:")
print(reshape_1x28)


# Task E2: Reshape into 2 × 14
reshape_2x14 = electricity.reshape(2, 14)

print("\nReshaped to 2x14:")
print(reshape_2x14)


Electricity Usage:
[[211 263 632 602 322 305 404]
 [554 339 298 249 364 165 642]
 [298 538 131 266 274 153 309]
 [249 405 326 614 194 394 259]]
Reshaped to 1x28:
[[211 263 632 602 322 305 404 554 339 298 249 364 165 642 298 538 131 266
  274 153 309 249 405 326 614 194 394 259]]

Reshaped to 2x14:
[[211 263 632 602 322 305 404 554 339 298 249 364 165 642]
 [298 538 131 266 274 153 309 249 405 326 614 194 394 259]]


# 🔄 Part E — Reshaping & Data Structure

Reshaping changes the **structure** of an array without changing its data.

Original electricity array shape:

```
(4, 7) → total elements = 28
```

Important rule:

```
Total elements must remain the same
```

---

## 🧠 Task E1: Reshape to 1 × 28

```python
reshape_1x28 = electricity.reshape(1, 28)
```

This converts the matrix into a **single row**.

Shape becomes:

```
(1, 28)
```

All 28 values remain unchanged.

---

## 🧠 Task E2: Reshape to 2 × 14

```python
reshape_2x14 = electricity.reshape(2, 14)
```

This reorganizes data into:

```
(2, 14)
```

Still contains exactly 28 elements.

---

## ⭐ Key Reshape Rule

```
rows × columns must equal total elements
```

Examples:

* 1 × 28 = 28 ✅
* 2 × 14 = 28 ✅

---

## 🎯 Viva Line

> Reshaping changes array structure without altering data, as long as total elements remain constant.
