Task E1: The "Copy vs View" Challenge
- Create a backup of the marks array.
- Modify the original array (e.g - set marks[0,0] =0)
- Check if the backup array changed or remained original.

Discussion Question: why is it dangerous to use backup = marks instead of backup = marks.copy()?

here backup array also changed

In [5]:
import numpy as np

# Create a marks matrix
marks = np.array([
    [80, 75, 90],
    [60, 55, 70]
])
backup = marks
# When we do backup = marks
backup = marks

# Modify the original array
marks[0, 0] = 0

# Print both arrays to compare
print("Original marks after modification:")
print(marks)

print("\nBackup array:")
print(backup)

Original marks after modification:
[[ 0 75 90]
 [60 55 70]]

Backup array:
[[ 0 75 90]
 [60 55 70]]


but here updated array changed the copied remain as it is

In [ ]:
import numpy as np

# Create a marks matrix
marks = np.array([
    [80, 75, 90],
    [60, 55, 70]
])

# Create a backup copy of the marks array
backup = marks.copy()

# Modify the original array
marks[0, 0] = 0

# Print both arrays to compare
print("Original marks after modification:")
print(marks)

print("\nBackup array:")
print(backup)


Original marks after modification:
[[ 0 75 90]
 [60 55 70]]

Backup array:
[[ 0 75 90]
 [60 55 70]]


# 🧪 Task E1: The "Copy vs View" Challenge

## 📌 Step 1: Create a Backup Copy

We create a backup of the original array using:

```python
backup = marks.copy()
```

`.copy()` creates a **new independent array in memory**.

---

## 📌 Step 2: Modify Original Array

```python
marks[0,0] = 0
```

This changes only the original array.

---

## 📌 Step 3: Compare Arrays

When printed:

* The **original array changes**
* The **backup remains unchanged**

This proves `.copy()` creates a separate object.

---

## ⚠️ Discussion: Why is `backup = marks` Dangerous?

If we write:

```python
backup = marks
```

then both variables point to the **same memory location**.

So:

👉 Changing `marks` will also change `backup`.

This is dangerous because:

* You may accidentally overwrite original data
* Data preprocessing becomes unreliable
* Bugs become hard to detect

---

## 🎯 Viva Line

> `.copy()` creates an independent duplicate array, while simple assignment creates a reference to the same data.
