Case Study : Dataset Description

A university monitors electricity usage (in units) of 4 hostels over 7 days (Mon-Sun).

Array name :  electricity
shape: (4,7)
rows : hostels(h1,h2,h3,h4)
columns : day(Mon-Sun)

Task A1:
Create numpy array electricity using np.random.randint
- Values between 120 and 650
- Shape (4,7)

Task A2: 
Print the following attributes of the array:
- Shape , Number of dimensions , Total number of elements , and datatype

# ⚡ Creating a 4×7 Electricity Usage Array with NumPy

## 🧠 Main Code Line

```python
electricity = np.random.randint(120, 651, (4, 7))
```

This single line generates a **4 × 7 matrix** of random electricity usage values.

---

## ✅ Part 1: Understanding `np.random.randint()`

`np.random.randint()` generates random integers.

### Syntax

```python
np.random.randint(low, high, size)
```

Where:

* **low** → starting value (included)
* **high** → ending value (excluded)
* **size** → shape of the output array

---

## ✅ Part 2: Range of Values (120 to 650)

```python
np.random.randint(120, 651, ...)
```

This generates values:

```
120 ≤ value < 651
```

So the actual range is:

```
120 to 650
```

⚠️ Important: The upper limit is **excluded**, so we use **651** to include 650.

---

## ✅ Part 3: Shape of the Array (4 × 7)

```python
(4, 7)
```

This specifies the matrix shape:

* **4 rows** → hostels (h1, h2, h3, h4)
* **7 columns** → days (Mon–Sun)

Total elements:

```
4 × 7 = 28 values
```

---

## 📊 Example Structure

```
Hostels ↓   Days →
           Mon Tue Wed Thu Fri Sat Sun
h1        [230 450 390 500 610 320 280]
h2        [410 380 270 600 490 520 310]
h3        [350 420 610 300 280 450 500]
h4        [290 370 480 510 340 620 400]
```

Each row represents a hostel and each column represents a day.

---

## ⭐ Simple Rule to Remember

```
np.random.randint(start, end, (rows, columns))
```

Rows × Columns determine the matrix size.

---

## 🎯 Viva Line

> `np.random.randint` generates random integers within a specified range and arranges them into a matrix of a given shape.


In [1]:
import numpy as np

# -----------------------------
# Task A1: Create electricity array
# -----------------------------

# Create a 4x7 array with random electricity usage
# Values range from 120 to 650
electricity = np.random.randint(120, 651, (4, 7))

# Print the generated array
print("Electricity Usage Array:")
print(electricity)

# -----------------------------
# Task A2: Print array attributes
# -----------------------------

# Print shape of the array
print("\nShape:", electricity.shape)

# Print number of dimensions
print("Number of dimensions:", electricity.ndim)

# Print total number of elements
print("Total elements:", electricity.size)

# Print datatype of elements
print("Data type:", electricity.dtype)


Electricity Usage Array:
[[465 168 604 514 378 364 386]
 [287 503 435 341 277 201 549]
 [511 180 383 556 421 584 287]
 [520 298 380 549 239 439 429]]

Shape: (4, 7)
Number of dimensions: 2
Total elements: 28
Data type: int64


# ⚡ Case Study: Electricity Usage Dataset

## 🧠 Task A1: Create the Dataset

We generate a NumPy array named **electricity** to simulate electricity usage of 4 hostels over 7 days.

```python
electricity = np.random.randint(120, 651, (4, 7))
```

* Values range from **120 to 650**
* Shape **(4, 7)** → 4 hostels × 7 days
* Each element represents electricity usage in units

---

## 📊 Task A2: Array Attributes

We inspect important properties of the dataset:

```python
electricity.shape   # returns (4, 7)
electricity.ndim    # returns 2
electricity.size    # returns 28
electricity.dtype   # returns integer datatype
```

### Meaning of Attributes

* **Shape** → rows × columns of the array
* **Dimensions** → number of axes (2D matrix)
* **Size** → total number of elements
* **Datatype** → type of stored values

---

## 🎯 Viva Line

> This dataset simulates electricity consumption using a 2D NumPy array, and its attributes describe structure and storage details.
