In [1]:
import numpy as np

# -----------------------------------
# Task 2.1: Increase all sales values by 2
# -----------------------------------
arr2 = np.array([
    [10, 15, 8, 12],
    [5, 7, 4, 6],
    [2, 3, 2, 4]
])
print("Updated sales data (+2):")
print(arr2 + 2)


# -----------------------------------
# Task 2.2: Calculate total revenue for each day
# Multiply cost price array by daily sales matrix
# -----------------------------------

# Cost price for each day
cost_price = np.array([20, 30, 15, 25])

# Revenue calculation using NumPy broadcasting
revenue = arr2 * cost_price

print("\nRevenue matrix:")
print(revenue)


# -----------------------------------
# Task 2.3: Scaling – Square root of sales data
# -----------------------------------
print("\nSquare root of sales data:")
print(np.sqrt(arr2))


Updated sales data (+2):
[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]

Revenue matrix:
[[200 450 120 300]
 [100 210  60 150]
 [ 40  90  30 100]]

Square root of sales data:
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]
