Task C1 : Pass / Fail mapping
- Create a status matrix where:
-- Mark >=50 ->1 (Pass)
-- Mark <=50 ->0 (Fail)

Task C2: Data Cleaning
- To standardize failing grades , replace all the marks below 40 with the value of 0.

# 🎯 NumPy Matrix: Pass/Fail Mapping + Data Cleaning

## 🧠 Step 1: Create a Marks Matrix

A **matrix** is a 2D NumPy array (rows + columns) used to store structured data.

```python
import numpy as np

marks = np.array([
    [35, 50, 72],
    [28, 90, 45]
])
```

👉 This is a **2 × 3 marks matrix**.

---

## ✅ Step 2: Pass / Fail Mapping (Using `np.where()`)

### 🔍 What is `np.where()`?

`np.where()` is used to apply **conditions on the whole matrix at once** (no loops needed 🚀).

📌 Syntax:

```
np.where(condition, value_if_true, value_if_false)
```

👉 It checks every element and assigns values based on the condition.

### 🎯 Our rule:

* Marks ≥ 50 → **1 (Pass)** ✅
* Marks < 50 → **0 (Fail)** ❌

```python
status = np.where(marks >= 50, 1, 0)
print(status)
```

📊 Output:

```
[[0 1 1]
 [0 1 0]]
```

👉 Each mark is converted into **Pass/Fail status**.

---

## 🧹 Step 3: Data Cleaning (Boolean Indexing)

We want to standardize failing grades:

👉 All marks **below 40 → replace with 0**

```python
marks[marks < 40] = 0
print(marks)
```
📊 Output:

```
[[ 0 50 72]
 [ 0 90 45]]
```

💡 This uses **boolean indexing** to update values instantly.

---

## 🧪 Final Combined Code

```python
import numpy as np

# Create marks matrix
marks = np.array([
    [35, 50, 72],
    [28, 90, 45]
])

# Pass/Fail mapping
status = np.where(marks >= 50, 1, 0)

# Data cleaning
marks[marks < 40] = 0

print("Status Matrix:")
print(status)

print("Cleaned Marks Matrix:")
print(marks)
```

---
## 🚀 Why Use `np.where()`?

`np.where()` is powerful because it:

✨ Applies conditions to the entire matrix at once
⚡ Avoids slow loops
📊 Is widely used in ML data preprocessing
🎯 Helps in classification & feature transformation

👉 In short: **Fast + Clean + Smart coding!**

In [1]:
import numpy as np
# Create a 2D matrix of student marks
marks = np.array([
    [35,50,72],
    [28,90,45]
])
# -----------------------------
# Task C1: Pass / Fail mapping
# -----------------------------

# Create a status matrix:
# Marks >= 50 → 1 (Pass)
# Marks < 50 → 0 (Fail)
status = np.where(marks >= 50, 1, 0)

# Print pass/fail matrix
print("Status Matrix:")
print(status)

Status Matrix:
[[0 1 1]
 [0 1 0]]


In [2]:
# -----------------------------
# Task C2: Data Cleaning
# -----------------------------

# Replace all marks below 40 with 0
# This standardizes failing grades
marks[marks < 40] = 0

# Print cleaned marks matrix
print("Cleaned Marks Matrix:")
print(marks)

Cleaned Marks Matrix:
[[ 0 50 72]
 [ 0 90 45]]
